### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by deurk** [liamcain/obsidian-periodic-notes#164] opened 2022-12-29 14:40 UTC
It is so convenient yet seems to receive very few updates since last year even though it is one of the most popular plugin. Would be a shame to let it rot... Maybe find a few new maintainers?

**Comment by liamcain** [comment] 2022-12-29 16:34
Closing this since it's a duplicate of #158

**Closed by liamcain** 2022-12-29 16:34 UTC
